### ISSUE TITLE
Fix WARNING: org.clojure/tools.nrepl version null is older than required 0.2.10

### ISSUE THREAD

**Issue by martinklepsch** [adzerk-oss/boot-cljs-repl#28] opened 2015-09-25 21:57 UTC
This warning appears every now and then. Usually requirements are met and there's "nothing to be warned about" so probably the mechanism triggering it is a bit off.

**Comment by Deraen** [comment] 2015-11-02 21:14
Duplicate of #19

**Closed by Deraen** 2015-11-02 21:14 UTC
